# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeus < Formula
  desc "An Electrifying Build System"
  homepage "https://github.com/dreadl0ck/zeus"
  version "0.9.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dreadl0ck/zeus/releases/download/v0.9.10/zeus_0.9.10_darwin_amd64.tar.gz"
      sha256 "0adc22480e426ce21dcd52550cdb91a63cc0cd335ac2ce105d0fc0af19b02d84"

      def install
        bin.install "zeus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dreadl0ck/zeus/releases/download/v0.9.10/zeus_0.9.10_linux_amd64.tar.gz"
      sha256 "d5e1abfaa19ab0090cf746c685ebb6673b4b57bcdde91b4e56d5d07e6bd93bcc"

      def install
        bin.install "zeus"
      end
    end
  end
end
